{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "gitea.serviceAccountName" . }}
  labels:
{{ include "gitea.labels" . | indent 4 }}
{{- end -}}
